services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - app_data:/app/resources/data
      - app_logs:/app/resources/logs

volumes:
  app_data:
  app_logs:
