name: main-workflow
run-name: ${{ github.actor }} is testing changes
on: [ push, pull_request ]

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13" ]
        poetry-version: [ "latest", "main", "1.8.4" ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
      - name: Setup Poetry
        uses: pronovic/setup-poetry@v2
        with:
          version: "1.8.0"
          plugins: "poetry-dynamic-versioning==1.2.0"
          cache-venv: "true"
          cache-poetry: "true"
      - name: Install the project dependencies
        run: poetry install
      - name: Run the automated tests (for example)
        run: poetry run pytest -v